import os
import sys
sys.path.append(os.getcwd())

from src.skills import video_skill

# Configuration from autonomous_producer.py run
BACKGROUND_IMAGE = r"C:\Users\mus-1\.gemini\antigravity\brain\3dbdae44-7314-4aa1-8a9d-3879dfa0c8a1\gezellig_nl_wellness_hydration_bg_1774969016414.png"
OUTPUT_FILENAME = "glowup_nl_wellness_otonom_v2.mp4"

# Audio Fragments (generated by autonomous_producer.py)
FRAGMENTS = [
    {"tag": "hook", "text": "Maak je dag gezelliger!", "audio": "outputs/autonorm_frag_0_hook.mp3"},
    {"tag": "content", "text": "Wist je dat hydratatie wonderen doet voor je humeur én je huid? Begin je dag met een groot glas water vóór je koffie of thee.", "audio": "outputs/autonorm_frag_1_content.mp3"},
    {"tag": "cta", "text": "Like & Save voor meer gezellige tips!", "audio": "outputs/autonorm_frag_2_cta.mp3"}
]

def render_final():
    print(f"🎬 Stüdyo hazırlanıyor: {OUTPUT_FILENAME}")
    
    # Ensure background image exists
    if not os.path.exists(BACKGROUND_IMAGE):
        print(f"❌ Background image not found: {BACKGROUND_IMAGE}")
        return

    # Call the production engine
    video_skill.create_reel(
        fragments=FRAGMENTS,
        output_filename=OUTPUT_FILENAME,
        image_path=BACKGROUND_IMAGE
    )
    
    print(f"✅ Render tamamlandı! Çıktı: outputs/{OUTPUT_FILENAME}")

if __name__ == "__main__":
    render_final()
